load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "repository",
    srcs = ["repository.go"],
    importpath = "example.com/my_project/services/product-svc/internal/repository",
    visibility = ["//services/product-svc:__subpackages__"],
    deps = [
        "//services/product-svc/internal/domain",
        "@org_mongodb_go_mongo_driver_v2//bson",
        "@org_mongodb_go_mongo_driver_v2//mongo",
    ],
)
