load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "grpc-client",
    srcs = ["grpc-client.go"],
    importpath = "gocline.com/ws/pkg/core/grpc-client",
    visibility = ["//visibility:public"],
    deps = [
        "@org_golang_google_grpc//:grpc",
        "@org_golang_google_grpc//credentials/insecure",
    ],
)
