load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "core",
    srcs = [
        "config.go",
        "grpc-client.go",
        "http.go",
    ],
    importpath = "example.com/my_project/pkg/core",
    visibility = ["//visibility:public"],
    deps = [
        "@org_golang_google_grpc//:grpc",
        "@org_golang_google_grpc//credentials/insecure",
    ],
)
